

function classColorsCodes()
{
    var out = [

                {className: 'Snca_class', IdentifiedType: 'Snca_class', color: '#0000FF'},
                {className: 'Cplx2_class', IdentifiedType: 'Cplx2_class', color: '#0000FF'},
                {className: 'Lhx6_class', IdentifiedType: 'Lhx6_class', color: '#0000FF'},
                {className: 'Col25a1_class', IdentifiedType: 'Col25a1_class', color: '#0000FF'},
                {className: 'Pnoc_class', IdentifiedType: 'Pnoc_class', color: '#0000FF'},
                {className: 'Rab3c_class', IdentifiedType: 'Rab3c_class', color: '#0000FF'},
                {className: 'Gad1_class', IdentifiedType: 'Gad1_class', color: '#0000FF'},
                {className: 'Slc6a1_class', IdentifiedType: 'Slc6a1_class', color: '#0000FF'},
                {className: 'Th_class', IdentifiedType: 'Th_class', color: '#00B3FF'},
                {className: 'Crhbp_class', IdentifiedType: 'Crhbp_class', color: '#00B3FF'},
                {className: 'Sst_class', IdentifiedType: 'Sst_class', color: '#00B3FF'},
                {className: 'Npy_class', IdentifiedType: 'Npy_class', color: '#00B3FF'},
                {className: 'Synpr_class', IdentifiedType: 'Synpr_class', color: '#00B3FF'},
                {className: 'Chodl_class', IdentifiedType: 'Chodl_class', color: '#00B3FF'},
                {className: 'Cort_class', IdentifiedType: 'Cort_class', color: '#00B3FF'},
                {className: 'Reln_class', IdentifiedType: 'Reln_class', color: '#00B3FF'},
                {className: 'Serpini1_class', IdentifiedType: 'Serpini1_class', color: '#00B3FF'},
                {className: 'Satb1_class', IdentifiedType: 'Satb1_class', color: '#00B3FF'},
                {className: 'Grin3a_class', IdentifiedType: 'Grin3a_class', color: '#00B3FF'},
                {className: 'Tac1_class', IdentifiedType: 'Tac1_class', color: '#5C33FF'},
                {className: 'Pvalb_class', IdentifiedType: 'Pvalb_class', color: '#5C33FF'},
                {className: 'Kcnip2_class', IdentifiedType: 'Kcnip2_class', color: '#5C33FF'},
                {className: 'Thsd7a_class', IdentifiedType: 'Thsd7a_class', color: '#5C33FF'},
                {className: 'Cox6a2_class', IdentifiedType: 'Cox6a2_class', color: '#5C33FF'},
                {className: 'Chrm2_class', IdentifiedType: 'Chrm2_class', color: '#5C33FF'},
                {className: 'Id2_class', IdentifiedType: 'Id2_class', color: '#FF00E6'},
                {className: 'Hapln1_class', IdentifiedType: 'Hapln1_class', color: '#FF00E6'},
                {className: 'Gabrd_class', IdentifiedType: 'Gabrd_class', color: '#FF00E6'},
                {className: 'Cryab_class', IdentifiedType: 'Cryab_class', color: '#FF00E6'},
                {className: 'Kit_class', IdentifiedType: 'Kit_class', color: '#FF00E6'},
                {className: 'Ndnf_class', IdentifiedType: 'Ndnf_class', color: '#FF00E6'},
                {className: 'Nos1_class', IdentifiedType: 'Nos1_class', color: '#FF00E6'},
                {className: 'Lamp5_class', IdentifiedType: 'Lamp5_class', color: '#FF00E6'},
                {className: 'Cplx3_class', IdentifiedType: 'Cplx3_class', color: '#FF00E6'},
                {className: 'Cadps2_class', IdentifiedType: 'Cadps2_class', color: '#995C00'},
                {className: 'Cxcl14_class', IdentifiedType: 'Cxcl14_class', color: '#995C00'},
                {className: 'Ntng1_class', IdentifiedType: 'Ntng1_class', color: '#995C00'},
                {className: 'Cpne5_class', IdentifiedType: 'Cpne5_class', color: '#995C00'},
                {className: 'Rgs12_class', IdentifiedType: 'Rgs12_class', color: '#995C00'},
                {className: 'Sncg_class', IdentifiedType: 'Sncg_class', color: '#FF0000'},
                {className: 'Cnr1_class', IdentifiedType: 'Cnr1_class', color: '#FF0000'},
                {className: 'Cck_class', IdentifiedType: 'Cck_class', color: '#FF0000'},
                {className: 'Trp53i11_class', IdentifiedType: 'Trp53i11_class', color: '#FF0000'},
                {className: 'Sema3c_class', IdentifiedType: 'Sema3c_class', color: '#FF0000'},
                {className: 'Syt6_class', IdentifiedType: 'Syt6_class', color: '#FF0000'},
                {className: 'Yjefn3_class', IdentifiedType: 'Yjefn3_class', color: '#FF0000'},
                {className: 'Rgs10_class', IdentifiedType: 'Rgs10_class', color: '#FF0000'},
                {className: 'Nov_class', IdentifiedType: 'Nov_class', color: '#FF0000'},
                {className: 'Kctd12_class', IdentifiedType: 'Kctd12_class', color: '#FF0000'},
                {className: 'Slc17a8_class', IdentifiedType: 'Slc17a8_class', color: '#FF0000'},
                {className: 'Tac2_class', IdentifiedType: 'Tac2_class', color: '#FFC700'},
                {className: 'Npy2r_class', IdentifiedType: 'Npy2r_class', color: '#FFC700'},
                {className: 'Calb2_class', IdentifiedType: 'Calb2_class', color: '#FFC700'},
                {className: 'Htr3a_class', IdentifiedType: 'Htr3a_class', color: '#FFC700'},
                {className: 'Slc5a7_class', IdentifiedType: 'Slc5a7_class', color: '#FFC700'},
                {className: 'Penk_class', IdentifiedType: 'Penk_class', color: '#FFC700'},
                {className: 'Pthlh_class', IdentifiedType: 'Pthlh_class', color: '#FFC700'},
                {className: 'Vip_class', IdentifiedType: 'Vip_class', color: '#FFC700'},
                {className: 'Crh_class', IdentifiedType: 'Crh_class', color: '#FFC700'},
                {className: 'Qrfpr_class', IdentifiedType: 'Qrfpr_class', color: '#FFC700'},
                {className: 'Zcchc12_class', IdentifiedType: 'Zcchc12_class', color: '#96B38F'},
                {className: 'Calb1_class', IdentifiedType: 'Calb1_class', color: '#96B38F'},
                {className: 'Vsnl1_class', IdentifiedType: 'Vsnl1_class', color: '#96B38F'},
                {className: 'Tmsb10_class', IdentifiedType: 'Tmsb10_class', color: '#96B38F'},
                {className: 'Rbp4_class', IdentifiedType: 'Rbp4_class', color: '#96B38F'},
                {className: 'Fxyd6_class', IdentifiedType: 'Fxyd6_class', color: '#96B38F'},
                {className: '6330403K07Rik_class', IdentifiedType: '6330403K07Rik_class', color: '#96B38F'},
                {className: 'Scg2_class', IdentifiedType: 'Scg2_class', color: '#96B38F'},
                {className: 'Gap43_class', IdentifiedType: 'Gap43_class', color: '#96B38F'},
                {className: 'Nrsn1_class', IdentifiedType: 'Nrsn1_class', color: '#96B38F'},
                {className: 'Gda_class', IdentifiedType: 'Gda_class', color: '#407F59'},
                {className: 'Bcl11b_class', IdentifiedType: 'Bcl11b_class', color: '#407F59'},
                {className: 'Rgs4_class', IdentifiedType: 'Rgs4_class', color: '#407F59'},
                {className: 'Slc24a2_class', IdentifiedType: 'Slc24a2_class', color: '#407F59'},
                {className: 'Lphn2_class', IdentifiedType: 'Lphn2_class', color: '#407F59'},
                {className: 'Adgrl2_class', IdentifiedType: 'Adgrl2_class', color: '#407F59'},
                {className: 'Map2_class', IdentifiedType: 'Map2_class', color: '#407F59'},
                {className: 'Prkca_class', IdentifiedType: 'Prkca_class', color: '#407F59'},
                {className: 'Cdh13_class', IdentifiedType: 'Cdh13_class', color: '#407F59'},
                {className: 'Atp1b1_class', IdentifiedType: 'Atp1b1_class', color: '#407F59'},
                {className: 'Pde1a_class', IdentifiedType: 'Pde1a_class', color: '#407F59'},
                {className: 'Calm2_class', IdentifiedType: 'Calm2_class', color: '#407F59'},
                {className: 'Sema3e_class', IdentifiedType: 'Sema3e_class', color: '#407F59'},
                {className: 'Nrn1_class', IdentifiedType: 'Nrn1_class', color: '#00FF00'},
                {className: 'Pcp4_class', IdentifiedType: 'Pcp4_class', color: '#00FF00'},
                {className: 'Rprm_class', IdentifiedType: 'Rprm_class', color: '#00FF00'},
                {className: 'Enpp2_class', IdentifiedType: 'Enpp2_class', color: '#00FF00'},
                {className: 'Rorb_class', IdentifiedType: 'Rorb_class', color: '#00FF00'},
                {className: 'Rasgrf2_class', IdentifiedType: 'Rasgrf2_class', color: '#00FF00'},
                {className: 'Wfs1_class', IdentifiedType: 'Wfs1_class', color: '#00FF00'},
                {className: 'Fos_class', IdentifiedType: 'Fos_class', color: '#00FF00'},
                {className: 'Plcxd2_class', IdentifiedType: 'Plcxd2_class', color: '#00FF00'},
                {className: 'Crym_class', IdentifiedType: 'Crym_class', color: '#00FF00'},
                {className: '3110035E14Rik_class', IdentifiedType: '3110035E14Rik_class', color: '#00FF00'},
                {className: 'Foxp2_class', IdentifiedType: 'Foxp2_class', color: '#00FF00'},
                {className: 'Pvrl3_class', IdentifiedType: 'Pvrl3_class', color: '#00FF00'},
                {className: 'Neurod6_class', IdentifiedType: 'Neurod6_class', color: '#44B300'},
                {className: 'Nr4a2_class', IdentifiedType: 'Nr4a2_class', color: '#44B300'},
                {className: 'Cux2_class', IdentifiedType: 'Cux2_class', color: '#44B300'},
                {className: 'Kcnk2_class', IdentifiedType: 'Kcnk2_class', color: '#44B300'},
                {className: 'Arpp21_class', IdentifiedType: 'Arpp21_class', color: '#44B300'},
                {className: 'Enc1_class', IdentifiedType: 'Enc1_class', color: '#44B300'},
                {className: 'Fam19a1_class', IdentifiedType: 'Fam19a1_class', color: '#44B300'},
                {className: 'Vim_class', IdentifiedType: 'Vim_class', color: '#FFFFFF'},
                {className: 'Slc1a2_class', IdentifiedType: 'Slc1a2_class', color: '#FFFFFF'},
                {className: 'Pax6_class', IdentifiedType: 'Pax6_class', color: '#FFFFFF'},
                {className: 'Plp1_class', IdentifiedType: 'Plp1_class', color: '#FFFFFF'},
                {className: 'Mal_class', IdentifiedType: 'Mal_class', color: '#FFFFFF'},
                {className: 'Aldoc_class', IdentifiedType: 'Aldoc_class', color: '#FFFFFF'},
                {className: 'Actb_class', IdentifiedType: 'Actb_class', color: '#FFFFFF'},
                {className: 'Sulf2_class', IdentifiedType: 'Sulf2_class', color: '#FFFFFF'},
                {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},



        // I added this
        {className: 'Other', IdentifiedType: 'Other', colorGroup: 'Other', color: '#C0C0C0'},


    ];

    return out
}